routes/web.php
<?php



Route::get('/', function () {
    return redirect('orders/customers');
})->middleware('auth');

Route::get( '/account/callback', '\Auth0\Login\Auth0Controller@callback' )->name( 'auth0-callback' );
Route::get('/login', 'Auth\Auth0IndexController@login' )->name( 'login' );
Route::get('/logout', 'Auth\Auth0IndexController@logout' )->name( 'logout' )->middleware('auth');

Route::group(['middleware' => 'auth'], function () {

    /**
     * Users
     */
    Route::group(['namespace' => 'Administration'], function () {
        Route::group(['middleware' => 'role:Admin,ABCorp Admin'], function () {
            Route::resource('users', 'UsersController');
            Route::post('users/{id}/update-roles', 'UsersController@updateRoles')->name('users.update-roles');
            Route::post('users/{id}/password-change', 'UsersController@passwordReset')->name('users.password-reset');
        });

        Route::post('users/updateTimezone', 'UsersController@updateTimezone')->name('users.update-timezone');
    });

    /**
     * Product Management
     */
    Route::group(['namespace' => 'ProductManagement', 'middleware' => 'role:AccountManager,ABCorp Account Manager,ABCorp Admin,OrderManager,OrderUser'], function () {
        Route::resource('management', 'ProductManagementController', ['only' => ['index', 'store']]);
        Route::resource('verticals', 'VerticalsController', ['only' => ['index', 'store']]);
        Route::resource('products', 'ProductsController', ['only' => ['store']]);
    });

    /**
     * Orders
     */
    Route::group(['prefix' => 'orders', 'namespace' => 'Orders', 'middleware' => 'role:OrderUser,OrderManager,RequestUser,RequestManager,ABCorp Account Manager,ABCorp Admin'], function () {
        /**
         * Customer orders
         */
        Route::get('customers', 'CustomerOrdersController@data')->name('customers.data');
        Route::post('customers', 'CustomerOrdersController@data');

        /**
         * Rejected items
         */
        Route::get('customers/{customer_order_uid}/rejected', 'RejectedItemsController@data')->name('rejected.data');
        Route::post('customers/{customer_order_uid}/rejected', 'RejectedItemsController@data');

        /**
         * Work orders
         */
        Route::group(['prefix' => 'work'], function () {
            Route::get('customer/{customer_order_uid}', 'WorkOrdersController@data')->name('work.customer');
            Route::post('customer/{customer_order_uid}', 'WorkOrdersController@data');
            Route::get('/', 'WorkOrdersController@data')->name('work.data');
            Route::post('/', 'WorkOrdersController@data');
        });
        Route::resource('work', 'WorkOrdersController', ['only' => ['show'],
            'parameters' => [
                'work' => 'work_order_uid'
            ]
        ]);

        /**
         * Order items
         */
        Route::resource('order-items', 'OrderItemsController', [
            'only' => ['index', 'show'],
        ]);
        Route::group(['prefix' => 'order-items'], function () {
            Route::post('{item_uid}/actions', 'OrderItemsController@actions')->name('order-items.actions');
            Route::post('action', 'OrderItemsController@action')->name('order-items.action');
            Route::get('order/{work_order_uid}', 'OrderItemsController@data')->name('order-items.order');
            Route::post('order/{work_order_uid}', 'OrderItemsController@data');
        });

        /**
         * Product Items
         */
        Route::get('product-items', 'ProductItemsController@data')->name('products.data');
        Route::post('product-items', 'ProductItemsController@data');

        /**
         * Customers requests
         */
        Route::group(['middleware' => 'role:RequestUser,RequestManager,ABCorp Account Manager,ABCorp Admin', 'prefix' => 'requests'], function () {
            Route::get('', 'CustomerRequestsController@data')->name('requests.data');
            Route::post('/{uid}/cancel', 'CustomerRequestsController@cancel')->name('requests.cancel');
            Route::post('', 'CustomerRequestsController@data');
        });
        Route::group(['middleware' => 'role:RequestManager,ABCorp Account Manager, ABCorp Admin'], function () {
            Route::resource('requests', 'CustomerRequestsController', ['only' => ['edit', 'update', 'show'], 'parameters' => [
                'request' => 'request_uid'
            ]]);
        });
    });

    Route::group(['namespace' => 'Reports', 'middleware' => 'role:ReportUser,ReportManager,ABCorp Account Manager,ABCorp Admin,OrderManager,OrderUser'], function () {
        /**
         * Reports
         */
        Route::group(['middleware' => 'role:ReportManager.ABCorp Account Manager,ABCorp Admin,OrderManager,OrderUser'], function () {
            Route::group(['prefix' => 'reports'], function () {
                Route::get('{report}/schedules', 'SchedulesController@data')->name('reports.schedules');
                Route::post('{report}/schedules', 'SchedulesController@data');
                Route::get('/schedules', 'SchedulesController@data')->name('schedules.data');
                Route::post('/schedules', 'SchedulesController@data');
                Route::get('/schedules/{uid}/{status}', 'SchedulesController@changeStatus')->name('schedules.change-status');
                Route::post('{report}/delivery', 'ReportsController@getDeliveryMethod');
            });

            Route::get('schedules/add/{report?}', 'SchedulesController@add')->name('schedules.add');
            Route::get('schedules/edit/{report?}', 'SchedulesController@edit')->name('schedules.edit');

            Route::resource('schedules', 'SchedulesController', ['only' => ['store']]);
        });

        Route::get('reports/{report}/{name?}', 'ReportsController@data')->name('reports.data');
        Route::post('reports/{report}/{name?}', 'ReportsController@data');
    });

    /**
     * Customers
     */
    Route::group(['prefix' => 'customers'], function () {
        Route::get('switch/{name}', 'CustomersController@switchCustomer')->name('customers.switch');
    });
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    private static $roles = [
        "ABCorp Account Manager",
        "ABCorp Admin",
        "Account Manager",
        "Admin",
        "Client Admin",
        "OrderUser",
        "OrderManager",
        "ReportUser",
        "ReportManager",
        "RequestUser",
        "RequestManager"
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * @return array
     */
    public static function getRoles(): array
    {
        return static::$roles;
    }

    /**
     * Check user role.
     *
     * @param string $role
     * @return bool
     */
    public static function hasRole(string $role)
    {
        if (self::isAdmin()) {
            return true;
        }

        if (array_search($role, auth()->user()->getUserInfo()['roles']) !== false) {
            return true;
        }

        return false;
    }

    private static function isAdmin()
    {
        if (array_search('Admin', auth()->user()->getUserInfo()['roles']) !== false) {
            return true;
        }

        return false;
    }

    public static function roleIn(array $roles)
    {
        if (self::isAdmin()) {
            return true;
        }

        foreach ($roles as $role) {
            if (in_array($role, auth()->user()->getUserInfo()['roles'])) {
                return true;
            }
        }

        return false;
    }
}

app/Http/Controllers/Administration/UsersController.php
<?php

namespace App\Http\Controllers\Administration;

use App\ABCorp\CWP\API\Auth0\GroupsRepositoryInterface;
use App\ABCorp\CWP\API\Auth0\RolesRepositoryInterface;
use App\ABCorp\CWP\API\Auth0\UserRepositoryInterface;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreUser;
use App\Http\Requests\UpdateUserRoles;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    /**
     * Get users that belong to the current customer.
     *
     * @param GroupsRepositoryInterface $groupsRepository
     * @return \Illuminate\View\View
     */
    public function index(GroupsRepositoryInterface $groupsRepository)
    {
        $members = $groupsRepository->getGroupMembers();

        return view('pages.administration.users.index', compact('members'));
    }

    /**
     * Show the form for creating a new user.
     *
     * @param RolesRepositoryInterface $rolesRepository
     * @return \Illuminate\Http\Response
     */
    public function create(RolesRepositoryInterface $rolesRepository)
    {
        return view('pages.administration.users.create')
            ->withRoles($rolesRepository->getRoles());
    }

    /**
     * Store a newly created user.
     *
     * @param StoreUser|Request $request
     * @param UserRepositoryInterface $userRepository
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUser $request, UserRepositoryInterface $userRepository)
    {
        $user = $userRepository->storeUser($request);

        if (isset($user->user_id)) {
            return redirect(route('users.show', $user->user_id))->with([
                'message' => 'The user was successfully stored.',
                'alert-type' => 'success',
            ]);
        }

        return redirect(route('users.index'))->with([
            'message' => 'Failed to store the user.',
            'alert-type' => 'error',
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @param UserRepositoryInterface $userRepository
     * @param RolesRepositoryInterface $rolesRepository
     * @return \Illuminate\Http\Response
     */
    public function show($id, UserRepositoryInterface $userRepository, RolesRepositoryInterface $rolesRepository)
    {
        $user = $userRepository->getUser($id);

        if (!$userRepository->valid($user)) {
            return redirect(route('users.index'));
        }

        $roles = $rolesRepository->getRoles();

        $user_roles = $userRepository->getUserRoles($user->user_id);

        return view('pages.administration.users.show', compact('user', 'roles', 'user_roles'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @param UserRepositoryInterface $userRepository
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, UserRepositoryInterface $userRepository)
    {
        $result = $userRepository->destroy($id);

        if (!$result) {
            return redirect(route('users.index'))->with([
                'message' => 'The user was successfully deleted.',
                'alert-type' => 'success',
            ]);
        }

        $error = json_decode($result);

        return redirect(route('users.index'))->with([
            'message' => $error->message,
            'alert-type' => 'error',
        ]);
    }

    /**
     * Update user roles.
     *
     * @param UpdateUserRoles $request
     * @param string $id
     * @param UserRepositoryInterface $userRepository
     * @return \Illuminate\Http\JsonResponse
     */
    public function updateRoles(UpdateUserRoles $request, string $id, UserRepositoryInterface $userRepository)
    {
        $user = $userRepository->getUser($id);

        if (!$userRepository->valid($user)) {
            return response()->json(['error' => $user, 'title' => 'Error']);
        }

        $user = $userRepository->updateRoles($user, $request->roles);

        if (isset($user->user_id)) {
            return response()->json(['message' => 'User roles has been successfully updated.']);
        }

        return response()->json(['error' => 'Failed to update user roles.']);
    }

    /**
     * Sent reset password link.
     *
     * @param string $id
     * @param UserRepositoryInterface $userRepository
     * @return \Illuminate\Http\JsonResponse
     */
    public function passwordReset(string $id, UserRepositoryInterface $userRepository)
    {
        $user = $userRepository->getUser($id);

        $result = $userRepository->changePassword([
            "client_id" => config('laravel-auth0.client_id'),
            "email" => $user->email,
            "connection" => "Username-Password-Authentication",
        ]);

        if ($result === null) {
            return response()->json([
                'title' => __('Password reset'),
                'message' => __('Email with password reset link was sent to the user'),
            ]);
        } else {
            return response()->json(['error' => $result, 'title' => 'Something goes wrong. Please try again later.']);
        }
    }

    public function updateTimezone(Request $request)
    {
        session()->put('timezone_offset', $request->timezone_offset);
    }
}

resources/views/pages/administration/users/create.blade.php
@extends('layouts.cwp')

@section('title', __('Add new user'))

@section('breadcrumb')
    <ol class="breadcrumb">
        <li>
            {{ __('Administration') }}
        </li>
        <li>
            <a href="{{ route('users.index') }}">
                {{ __('Users') }}
            </a>
        </li>
        <li class="active">
            <strong>{{ __('Add new user') }}</strong>
        </li>
    </ol>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-6">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <form method="post" class="form-horizontal" action="{{ route('users.store') }}">
                        {{ csrf_field() }}

                        <div class="form-group @if ($errors->has('email')) has-error @endif">
                            <label class="col-sm-2 control-label" for="email">Email</label>
                            <div class="col-sm-10">
                                <input type="email" class="form-control" name="email" id="email"
                                       value="{{ old('email') }}">
                                @if ($errors->has('email')) <p
                                        class="help-block">{{ $errors->first('email') }}</p> @endif
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-primary" type="submit">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('vendor-css')
    <link href="{{ asset('css/plugins/chosen/bootstrap-chosen.css') }}" rel="stylesheet">
@endpush

@push('vendor-scripts')
    <script src="{{ asset('js/plugins/chosen/chosen.jquery.js') }}"></script>
@endpush

@push('scripts')
    <script>
        $(document).ready(function () {
            $('.chosen-select').chosen();
        });
    </script>
@endpush

resources/views/pages/administration/users/index.blade.php
@extends('layouts.cwp')

@section('title', __('Users'))

@section('breadcrumb')
    <ol class="breadcrumb">
        <li>
            {{ __('Administration') }}
        </li>
        <li class="active">
            <strong>{{ __('Users') }}</strong>
        </li>
    </ol>
@endsection

@section('content')
    <div class="ibox-content m-b-md border-bottom p-top-xs-20 p-top-sm-20">
        <div class="row">
            <div class="col-md-2 col-xs-12 pull-right">
                <a href="{{ route('users.create') }}" class="btn btn-success btn-outline btn-xs-block pull-right">
                    <i class="fa fa-plus" aria-hidden="true"></i>
                    {{ __('Add new user') }}
                </a>
            </div>
        </div>
    </div>

    <div id="table">
        @include('pages.administration.users.table')
    </div>
@endsection

@push('scripts')
    <script>
        let offset_first = true;

        $(document).ready(function () {
            let columnDefs = initDTSearchFields();

            let table = $('#dataTable').DataTable({
                "dom": 'tp',
                "autoWidth": false,
                drawCallback: function (settings) {
                    let pagination = $(this).closest('.dataTables_wrapper').find('.dataTables_paginate');
                    pagination.toggle(this.api().page.info().pages > 1);
                },
                "columnDefs": columnDefs
            });

            DTIndividualSearch(table);
        });
    </script>
@endpush

resources/views/pages/administration/users/show.blade.php
@extends('layouts.cwp')

@section('title', __('Users info'))

@section('breadcrumb')
    <ol class="breadcrumb">
        <li>
            {{ __('Administration') }}
        </li>
        <li>
            <a href="{{ route('users.index') }}">
                {{ __('Users') }}
            </a>
        </li>
        <li class="active">
            <strong>{{ $user->nickname ?? 'No nickname' }}</strong>
        </li>
    </ol>
@endsection

@section('content')
    <div class="row m-b-lg m-t-lg">
        <div class="col-md-5">

            <div class="profile-image">
                <img src="{{ isset($user->user_metadata->picture) ? $user->user_metadata->picture : $user->picture }}"
                     class="img-circle circle-border m-b-md" alt="profile">
            </div>
            <div class="profile-info">
                <div class="">
                    <div>
                        <h2>
                            {{ $user->nickname ?? 'No nickname' }}
                        </h2>

                        <p>
                            <button class="btn btn-primary" id="password_reset"
                                    data-url="{{ route('users.password-reset', $user->user_id) }}">
                                <i class="fa fa-envelope"></i>
                                Send password reset link
                            </button>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <table class="table small m-b-xs">
                <tbody>
                <tr>
                    <td>ID: <strong>{{ $user->user_id }}</strong></td>
                    <td>Email Verified: <strong>{{ $user->email_verified ? 'Yes' : 'No' }}</strong></td>
                </tr>
                <tr>
                    <td>Email: <strong>{{ $user->email }}</strong></td>
                    <td>
                        Created at: <strong>{{ Carbon\Carbon::parse($user->created_at)->toDateTimeString() }}</strong>
                    </td>
                </tr>
                <tr>
                    <td>Name: <strong>{{ $user->name ?? 'No name' }}</strong></td>
                    <td>
                        Updated at: <strong>{{ Carbon\Carbon::parse($user->updated_at)->toDateTimeString() }}</strong>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-3">
            <small>Logins count</small>
            <h2 class="no-margins">{{ $user->logins_count ?? 0 }}</h2>

            @if (isset($user->last_login))
                <small>
                    Last login:
                    <strong>{{ Carbon\Carbon::parse($user->last_login)->toDateTimeString() }}</strong>
                </small>
            @endif
            <div id="sparkline1"></div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-3">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>User roles</h5>
                </div>
                <div class="ibox-content">
                    <form action="{{ route('users.update-roles', $user->user_id) }}" method="post" id="update-role">
                        <div class="form-group">
                            <select name="roles[]" data-placeholder="Choose roles" class="chosen-select" multiple
                                    style="width:350px;" id="roles" tabindex="4">
                                @foreach($roles as $key => $value)
                                    @if (in_array($value, $user_roles))
                                        <option value="{{ $key }}" selected> {{ $value }}</option>
                                    @else
                                        <option value="{{ $key }}"> {{ $value }}</option>
                                    @endif
                                @endforeach
                            </select>
                        </div>
                        <button type="button" class="btn btn-primary btn-sm btn-block" data-style="zoom-in">Update
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@push('scripts')
    <script>
        $(document).ready(function () {

            $('.chosen-select').chosen();

            $('#password_reset').on('click', function (e) {
                let l = Ladda.create(this);
                l.start();

                $.ajax({
                    type: 'POST',
                    url: $(this).data('url'),
                    success: function (data) {
                        if (data.error) {
                            toastr.error(data.error, data.title);
                        } else {
                            toastr.success(data.message, data.title);
                        }
                    }
                }).always(function () {
                    l.stop();
                });
            });

            $('#update-role').on('click', 'button', function (e) {

                let l = Ladda.create(this);
                l.start();

                $.ajax({
                    type: 'POST',
                    url: $('#update-role').attr('action'),
                    data: $('#update-role').serialize(),
                    success: function (data) {
                        if (data.error) {
                            toastr.error(data.error);
                        } else {
                            toastr.success(data.message);
                        }
                    }
                }).always(function () {
                    l.stop();
                });
            });
        });
    </script>
@endpush

resources/views/pages/administration/users/table.blade.php
<div class="row">
    <div class="col-lg-12">
        <div class="ibox">
            <div class="ibox-content table-data">
                @if (isset($members))
                    <div class="table-responsive">

                        <table class="table table-striped table-bordered table-hover" id="dataTable">
                            <thead>
                            <tr>
                                <th style="width: 50px;"></th>
                                <th>{{ __('Email') }}</th>
                                <th style="width: 100px;"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($members as $member)
                                <tr>
                                    <td>
                                        <img class="img-responsive img-circle"
                                             src="{{ isset($member->user_metadata->picture) ?
                                             $member->user_metadata->picture : $member->picture }}">
                                    </td>
                                    <td>
                                        {{ $member->email }}
                                    </td>
                                    <td class="text-center">
                                        <div style="width: 90px">
                                            <a href="{{ route('users.show', $member->user_id) }}"
                                               class="btn btn-outline btn-info" title="{{ __("User info") }}">
                                                <i class="fa fa-address-card-o" aria-hidden="true"></i>
                                            </a>

                                            <form action="{{ route('users.destroy', $member->user_id) }}" method="post"
                                                  style="display: inline">
                                                {{ method_field('DELETE') }}
                                                {{csrf_field()}}

                                                <button title="{{ __('Delete') }}" class="btn btn-outline btn-danger delete"
                                                        type="submit">
                                                    <i class="fa fa-trash" aria-hidden="true"></i>
                                                </button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                @else
                    <div class="alert alert-warning m-n">
                        {{ __('No data available.') }}
                    </div>
                @endif
            </div>
        </div>
    </div>
</div>