routes/web.php
<?php



Route::get('/', function () {
    return redirect('orders/customers');
})->middleware('auth');

Route::get( '/account/callback', '\Auth0\Login\Auth0Controller@callback' )->name( 'auth0-callback' );
Route::get('/login', 'Auth\Auth0IndexController@login' )->name( 'login' );
Route::get('/logout', 'Auth\Auth0IndexController@logout' )->name( 'logout' )->middleware('auth');

Route::group(['middleware' => 'auth'], function () {

    /**
     * Users
     */
    Route::group(['namespace' => 'Administration'], function () {
        Route::group(['middleware' => 'role:Admin,ABCorp Admin'], function () {
            Route::resource('users', 'UsersController');
            Route::post('users/{id}/update-roles', 'UsersController@updateRoles')->name('users.update-roles');
            Route::post('users/{id}/password-change', 'UsersController@passwordReset')->name('users.password-reset');
        });

        Route::post('users/updateTimezone', 'UsersController@updateTimezone')->name('users.update-timezone');
    });

    /**
     * Product Management
     */
    Route::group(['namespace' => 'ProductManagement', 'middleware' => 'role:AccountManager,ABCorp Account Manager,ABCorp Admin,OrderManager,OrderUser'], function () {
        Route::resource('management', 'ProductManagementController', ['only' => ['index', 'store']]);
        Route::resource('verticals', 'VerticalsController', ['only' => ['index', 'store']]);
        Route::resource('products', 'ProductsController', ['only' => ['store']]);
    });

    /**
     * Orders
     */
    Route::group(['prefix' => 'orders', 'namespace' => 'Orders', 'middleware' => 'role:OrderUser,OrderManager,RequestUser,RequestManager,ABCorp Account Manager,ABCorp Admin'], function () {
        /**
         * Customer orders
         */
        Route::get('customers', 'CustomerOrdersController@data')->name('customers.data');
        Route::post('customers', 'CustomerOrdersController@data');

        /**
         * Rejected items
         */
        Route::get('customers/{customer_order_uid}/rejected', 'RejectedItemsController@data')->name('rejected.data');
        Route::post('customers/{customer_order_uid}/rejected', 'RejectedItemsController@data');

        /**
         * Work orders
         */
        Route::group(['prefix' => 'work'], function () {
            Route::get('customer/{customer_order_uid}', 'WorkOrdersController@data')->name('work.customer');
            Route::post('customer/{customer_order_uid}', 'WorkOrdersController@data');
            Route::get('/', 'WorkOrdersController@data')->name('work.data');
            Route::post('/', 'WorkOrdersController@data');
        });
        Route::resource('work', 'WorkOrdersController', ['only' => ['show'],
            'parameters' => [
                'work' => 'work_order_uid'
            ]
        ]);

        /**
         * Order items
         */
        Route::resource('order-items', 'OrderItemsController', [
            'only' => ['index', 'show'],
        ]);
        Route::group(['prefix' => 'order-items'], function () {
            Route::post('{item_uid}/actions', 'OrderItemsController@actions')->name('order-items.actions');
            Route::post('action', 'OrderItemsController@action')->name('order-items.action');
            Route::get('order/{work_order_uid}', 'OrderItemsController@data')->name('order-items.order');
            Route::post('order/{work_order_uid}', 'OrderItemsController@data');
        });

        /**
         * Product Items
         */
        Route::get('product-items', 'ProductItemsController@data')->name('products.data');
        Route::post('product-items', 'ProductItemsController@data');

        /**
         * Customers requests
         */
        Route::group(['middleware' => 'role:RequestUser,RequestManager,ABCorp Account Manager,ABCorp Admin', 'prefix' => 'requests'], function () {
            Route::get('', 'CustomerRequestsController@data')->name('requests.data');
            Route::post('/{uid}/cancel', 'CustomerRequestsController@cancel')->name('requests.cancel');
            Route::post('', 'CustomerRequestsController@data');
        });
        Route::group(['middleware' => 'role:RequestManager,ABCorp Account Manager, ABCorp Admin'], function () {
            Route::resource('requests', 'CustomerRequestsController', ['only' => ['edit', 'update', 'show'], 'parameters' => [
                'request' => 'request_uid'
            ]]);
        });
    });

    Route::group(['namespace' => 'Reports', 'middleware' => 'role:ReportUser,ReportManager,ABCorp Account Manager,ABCorp Admin,OrderManager,OrderUser'], function () {
        /**
         * Reports
         */
        Route::group(['middleware' => 'role:ReportManager.ABCorp Account Manager,ABCorp Admin,OrderManager,OrderUser'], function () {
            Route::group(['prefix' => 'reports'], function () {
                Route::get('{report}/schedules', 'SchedulesController@data')->name('reports.schedules');
                Route::post('{report}/schedules', 'SchedulesController@data');
                Route::get('/schedules', 'SchedulesController@data')->name('schedules.data');
                Route::post('/schedules', 'SchedulesController@data');
                Route::get('/schedules/{uid}/{status}', 'SchedulesController@changeStatus')->name('schedules.change-status');
                Route::post('{report}/delivery', 'ReportsController@getDeliveryMethod');
            });

            Route::get('schedules/add/{report?}', 'SchedulesController@add')->name('schedules.add');
            Route::get('schedules/edit/{report?}', 'SchedulesController@edit')->name('schedules.edit');

            Route::resource('schedules', 'SchedulesController', ['only' => ['store']]);
        });

        Route::get('reports/{report}/{name?}', 'ReportsController@data')->name('reports.data');
        Route::post('reports/{report}/{name?}', 'ReportsController@data');
    });

    /**
     * Customers
     */
    Route::group(['prefix' => 'customers'], function () {
        Route::get('switch/{name}', 'CustomersController@switchCustomer')->name('customers.switch');
    });
});

resources/views/partials/menus/left.blade.php
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">

            <li class="nav-header">
                <div class="dropdown profile-element text-center">
                    <span>
                        @if (isset(auth()->user()->getUserInfo()['user_metadata']['picture']))
                            <img alt="image" class="img-responsive text-center"
                                 src="{{ auth()->user()->getUserInfo()['user_metadata']['picture'] }}"
                                 style="margin: 0 auto;"/>
                        @else
                            <img alt="image" class="img-responsive text-center" src="{{ auth()->user()->picture }}"
                                 style="margin: 0 auto;"/>
                        @endif

                    </span>

                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">{{ auth()->user()->nickname }}</strong>
                            </span>
                        </span>
                    </a>
                </div>
                <div class="logo-element">
                    CWP
                </div>
            </li>

            @if (\App\User::roleIn(['Admin', 'ABCorp Admin']))
                <li @if (in_array(request()->segment(1), ['users'])) class="active" @endif>
                    <a href="#">
                        <i class="fa fa-shield" aria-hidden="true"></i>
                        <span class="nav-label">{{ __('Administration') }}</span>
                        <span class="fa arrow"></span>
                    </a>
                    <ul class="nav nav-second-level collapse">
                        <li @if (in_array(request()->segment(1), ['users'])) class="active" @endif>
                            <a href="{{ route('users.index') }}">
                                <i class="fa fa-user-circle" aria-hidden="true"></i>
                                {{ __('Users') }}
                            </a>
                        </li>
                    </ul>
                </li>
            @endif

            @if (\App\User::roleIn(['AccountManager', 'ABCorp Account Manager', 'ABCorp Admin']))
                <li @if (in_array(request()->segment(1), ['management'])) class="active" @endif>
                    <a href="{{ route('management.index') }}">
                        <i class="fa fa-cube" aria-hidden="true"></i>
                        <span class="nav-label">{{ __('Product and Parts') }}</span>
                    </a>
                </li>
            @endif

            @if (\App\User::roleIn(['ABCorp Account Manager', 'ABCorp Admin', 'OrderUser', 'OrderManager', 'RequestUser', 'RequestManager']))
                <li class="landing_link">
                    <a href="{{ route('products.data') }}">
                        <i class="fa fa-search" aria-hidden="true"></i>
                        <span class="nav-label">Search</span>
                    </a>
                </li>

                <li @if (in_array(request()->segment(1), ['orders', 'work', 'products', 'requests', ])) class="active" @endif>
                    <a href="#">
                        <i class="fa fa-list"></i>
                        <span class="nav-label">{{ __('cwp.orders.title') }}</span>
                        <span class="fa arrow"></span>
                    </a>
                    <ul class="nav nav-second-level collapse">
                        <li @if (request()->routeIs('customers.data') or request()->routeIs('rejected.data')) class="active" @endif>
                            <a href="{{ route('customers.data') }}">{{ __('Customer Orders') }}</a>
                        </li>

                        <li @if (request()->routeIs('work.data') or
                                request()->routeIs('order-items.order') or
                                request()->routeIs('work.show') or
                                request()->routeIs('work.customer')) class="active" @endif>
                            <a href="{{ route('work.data') }}">{{ __('Work Orders') }}</a>
                        </li>

                        <li @if (request()->routeIs('products.data')) class="active" @endif>
                            <a href="{{ route('products.data') }}">{{ __('Product Items') }}</a>
                        </li>

                        @if (\App\User::roleIn(['ABCorp Account Manager', 'ABCorp Admin', 'OrderManager', 'OrderUser', 'RequestUser', 'RequestManager']))
                            <li @if (request()->routeIs('requests.data') or request()->routeIs('requests.show')) class="active" @endif>
                                <a href="{{ route('requests.data') }}">{{ __('Customer Requests') }}</a>
                            </li>
                        @endif
                    </ul>
                </li>

            @endif

            @if (\App\User::roleIn(['ABCorp Account Manager', 'ABCorp Admin', 'OrderManager', 'OrderUser', 'ReportUser', 'ReportManager']))
                <li @if (request()->segment(1) == 'reports') class="active" @endif>
                    <a href="#">
                        <i class="fa fa-file-text-o" aria-hidden="true"></i>
                        <span class="nav-label">{{ __('cwp.reports.title') }}</span>
                        <span class="fa arrow"></span>
                    </a>

                    <ul class="nav nav-second-level collapse">
                        @if (isset($reports->data) && !empty($reports->data))
                            @foreach($reports->data as $report)
                                <li @if (request()->segment(2) === $report->uid) class="active" @endif>
                                    <a href="{{ route('reports.data', ['report' => $report->uid, 'name' => $report->name]) }}">{{ $report->name }}</a>
                                </li>
                            @endforeach
                        @endif

                        @if (\App\User::roleIn(['ABCorp Account Manager', 'ABCorp Admin', 'Client Admin']))
                            <li @if (request()->routeIs('schedules.data') ) class="active" @endif>
                                <a href="{{ route('schedules.data') }}">{{ __('cwp.reports.schedule.title') }}</a>
                            </li>
                        @endif
                    </ul>
                </li>
            @endif

            <li class="special_link visible-xs-inline-block">
                <a href="{{ route('logout') }}">
                    <i class="fa fa-sign-out"></i>
                    <span class="nav-label">Log out</span>
                </a>
            </li>

        </ul>

        <div class="logo">
            <a href="http://www.abnote.com">
                <img src="{{ asset('images/logo_white.png') }}" class="img-responsive">
            </a>
        </div>
    </div>
</nav>

resources/views/partials/menus/top.blade.php
<div class="row border-bottom">
    <nav class="navbar navbar-static-top  " role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary" href="#"><i class="fa fa-bars"></i> </a>
        </div>

        @if (isset($customers) && count($customers))
            <ul class="nav navbar-top-links navbar-left">
                <li class="dropdown select-customer">
                    <select data-placeholder="Choose a customer..." class="customer-select" style="padding: 20px 10px">
                        @foreach($customers as $dataPrepID => $customer)
                            <option value="{{ $dataPrepID }}" @if ($customerName == $dataPrepID) selected @endif>
                                {{ $customer }}
                            </option>
                        @endforeach
                    </select>
                </li>
            </ul>
        @endif

        <ul class="nav navbar-top-links navbar-right">
            <li>
                <span class="m-r-sm text-muted welcome-message">
                    Welcome to <a href="http://abcorp.com/">ABCorp</a> {{ config('app.name') }}
                </span>
            </li>
            <li class="hidden-xs">
                <a href="{{ route('logout') }}">
                    <i class="fa fa-sign-out"></i> Log out
                </a>
            </li>
        </ul>
    </nav>
</div>