routes/web.php
<?php



Route::get('/', function () {
    return redirect('orders/customers');
})->middleware('auth');

Route::get( '/account/callback', '\Auth0\Login\Auth0Controller@callback' )->name( 'auth0-callback' );
Route::get('/login', 'Auth\Auth0IndexController@login' )->name( 'login' );
Route::get('/logout', 'Auth\Auth0IndexController@logout' )->name( 'logout' )->middleware('auth');

Route::group(['middleware' => 'auth'], function () {

    /**
     * Users
     */
    Route::group(['namespace' => 'Administration'], function () {
        Route::group(['middleware' => 'role:Admin,ABCorp Admin'], function () {
            Route::resource('users', 'UsersController');
            Route::post('users/{id}/update-roles', 'UsersController@updateRoles')->name('users.update-roles');
            Route::post('users/{id}/password-change', 'UsersController@passwordReset')->name('users.password-reset');
        });

        Route::post('users/updateTimezone', 'UsersController@updateTimezone')->name('users.update-timezone');
    });

    /**
     * Product Management
     */
    Route::group(['namespace' => 'ProductManagement', 'middleware' => 'role:AccountManager,ABCorp Account Manager,ABCorp Admin,OrderManager,OrderUser'], function () {
        Route::resource('management', 'ProductManagementController', ['only' => ['index', 'store']]);
        Route::resource('verticals', 'VerticalsController', ['only' => ['index', 'store']]);
        Route::resource('products', 'ProductsController', ['only' => ['store']]);
    });

    /**
     * Orders
     */
    Route::group(['prefix' => 'orders', 'namespace' => 'Orders', 'middleware' => 'role:OrderUser,OrderManager,RequestUser,RequestManager,ABCorp Account Manager,ABCorp Admin'], function () {
        /**
         * Customer orders
         */
        Route::get('customers', 'CustomerOrdersController@data')->name('customers.data');
        Route::post('customers', 'CustomerOrdersController@data');

        /**
         * Rejected items
         */
        Route::get('customers/{customer_order_uid}/rejected', 'RejectedItemsController@data')->name('rejected.data');
        Route::post('customers/{customer_order_uid}/rejected', 'RejectedItemsController@data');

        /**
         * Work orders
         */
        Route::group(['prefix' => 'work'], function () {
            Route::get('customer/{customer_order_uid}', 'WorkOrdersController@data')->name('work.customer');
            Route::post('customer/{customer_order_uid}', 'WorkOrdersController@data');
            Route::get('/', 'WorkOrdersController@data')->name('work.data');
            Route::post('/', 'WorkOrdersController@data');
        });
        Route::resource('work', 'WorkOrdersController', ['only' => ['show'],
            'parameters' => [
                'work' => 'work_order_uid'
            ]
        ]);

        /**
         * Order items
         */
        Route::resource('order-items', 'OrderItemsController', [
            'only' => ['index', 'show'],
        ]);
        Route::group(['prefix' => 'order-items'], function () {
            Route::post('{item_uid}/actions', 'OrderItemsController@actions')->name('order-items.actions');
            Route::post('action', 'OrderItemsController@action')->name('order-items.action');
            Route::get('order/{work_order_uid}', 'OrderItemsController@data')->name('order-items.order');
            Route::post('order/{work_order_uid}', 'OrderItemsController@data');
        });

        /**
         * Product Items
         */
        Route::get('product-items', 'ProductItemsController@data')->name('products.data');
        Route::post('product-items', 'ProductItemsController@data');

        /**
         * Customers requests
         */
        Route::group(['middleware' => 'role:RequestUser,RequestManager,ABCorp Account Manager,ABCorp Admin', 'prefix' => 'requests'], function () {
            Route::get('', 'CustomerRequestsController@data')->name('requests.data');
            Route::post('/{uid}/cancel', 'CustomerRequestsController@cancel')->name('requests.cancel');
            Route::post('', 'CustomerRequestsController@data');
        });
        Route::group(['middleware' => 'role:RequestManager,ABCorp Account Manager, ABCorp Admin'], function () {
            Route::resource('requests', 'CustomerRequestsController', ['only' => ['edit', 'update', 'show'], 'parameters' => [
                'request' => 'request_uid'
            ]]);
        });
    });

    Route::group(['namespace' => 'Reports', 'middleware' => 'role:ReportUser,ReportManager,ABCorp Account Manager,ABCorp Admin,OrderManager,OrderUser'], function () {
        /**
         * Reports
         */
        Route::group(['middleware' => 'role:ReportManager.ABCorp Account Manager,ABCorp Admin,OrderManager,OrderUser'], function () {
            Route::group(['prefix' => 'reports'], function () {
                Route::get('{report}/schedules', 'SchedulesController@data')->name('reports.schedules');
                Route::post('{report}/schedules', 'SchedulesController@data');
                Route::get('/schedules', 'SchedulesController@data')->name('schedules.data');
                Route::post('/schedules', 'SchedulesController@data');
                Route::get('/schedules/{uid}/{status}', 'SchedulesController@changeStatus')->name('schedules.change-status');
                Route::post('{report}/delivery', 'ReportsController@getDeliveryMethod');
            });

            Route::get('schedules/add/{report?}', 'SchedulesController@add')->name('schedules.add');
            Route::get('schedules/edit/{report?}', 'SchedulesController@edit')->name('schedules.edit');

            Route::resource('schedules', 'SchedulesController', ['only' => ['store']]);
        });

        Route::get('reports/{report}/{name?}', 'ReportsController@data')->name('reports.data');
        Route::post('reports/{report}/{name?}', 'ReportsController@data');
    });

    /**
     * Customers
     */
    Route::group(['prefix' => 'customers'], function () {
        Route::get('switch/{name}', 'CustomersController@switchCustomer')->name('customers.switch');
    });
});

app/Http/Controllers/Orders/CustomerOrdersController.php
<?php

namespace App\Http\Controllers\Orders;

use App\ABCorp\CWP\API\CustomerOrders;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CustomerOrdersController extends Controller
{
    private $customerOrders;

    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            $this->customerOrders = new CustomerOrders;

            return $next($request);
        });
    }

    /**
     * Get customer orders.
     *
     * @param Request $request
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\JsonResponse|\Illuminate\View\View
     * @throws \Throwable
     */
    public function data(Request $request)
    {
        $data = $this->customerOrders->customerOrders([
            'currentpage' => $this->getCurrentPage($request),
            'startDateTime' => $this->getStartDate($request, true),
            'endDateTime' => $this->getEndDate($request, true),
        ]);

        return $this->response('pages.orders.customers', $request, [
            'data' => $data,
            'date_from' => $this->getStartDate($request),
            'date_to' => $this->getEndDate($request),
        ]);
    }
}

app/Http/Controllers/Orders/CustomerRequestsController.php
<?php

namespace App\Http\Controllers\Orders;

use App\ABCorp\CWP\API\CustomerRequests;
use App\Http\Controllers\Controller;
use App\Http\Requests\UpdateCustomerRequest;
use Illuminate\Http\Request;

class CustomerRequestsController extends Controller
{
    private $customerRequests;

    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            $this->customerRequests = new CustomerRequests;

            return $next($request);
        });
    }

    /**
     * Get customers requests.
     *
     * @param Request $request
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\JsonResponse|\Illuminate\View\View
     * @throws \Throwable
     */
    public function data(Request $request)
    {
        $data = $this->customerRequests->itemActions([
            'currentpage' => $this->getCurrentPage($request),
            'statuses' => isset($request->statuses) ? $request->statuses : [],
            'actions' => isset($request->actions) ? $request->actions : [],
            'startDateTime' => $this->getStartDate($request, true),
            'endDateTime' => $this->getEndDate($request, true),
        ]);

        return $this->response('pages.orders.requests', $request, [
            'data' => $data,
            'date_from' => $this->getStartDate($request),
            'date_to' => $this->getEndDate($request),
        ]);
    }

    /**
     * Cancel customer request.
     *
     * @param string $uid
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function cancel(string $uid)
    {
        $results = $this->customerRequests->updateItemActionStatus([
            'itemActioRequestUid' => $uid,
            'status' => 'Cancelled',
        ]);

        if (isset($results->success) && $results->success) {
            return response()->json([
                'title' => __('cwp.requests.cancel.title'),
                'message' => __('cwp.requests.cancel.message'),
            ]);
        }

        return response()->json(['error' => $results, 'title' => 'Error']);
    }

    /**
     * Get details for the customer request.
     *
     * @param string $uid
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Throwable
     */
    public function details(string $uid)
    {
        $data = $this->customerRequests->itemActionDetails($uid);

        return view('pages.orders.requests.details', compact('data'))->render();
    }

    public function show(string $uid)
    {
        $data = $this->customerRequests->itemActionDetails($uid);

        $requestDetails = json_decode($data->details->requestDetails);

        $shippingDetail = (array)$requestDetails->shippingDetail;

        $rushForwardRequested = $requestDetails->rushForwardRequested;

        return view('pages.orders.requests.show', compact('data', 'shippingDetail', 'rushForwardRequested'));
    }

    /**
     * Get view for update modal.
     *
     * @param string $request
     *
     * @return string
     * @throws \Throwable
     */
    public function edit(string $request)
    {
        $data = $this->customerRequests->itemActionDetails($request);

        $statuses = $this->customerRequests->getStatuses();

        $carriers = $this->customerRequests->getCarriers();

        return view('pages.orders.requests.update-form', compact('data', 'statuses', 'carriers'))->render();
    }

    /**
     * Update customer request.
     *
     * @param string $request_uid
     * @param UpdateCustomerRequest $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(string $request_uid, UpdateCustomerRequest $request)
    {
        $results = $this->customerRequests->updateItemActionStatus([
            'itemActioRequestUid' => $request_uid,
            'actionData' => $request->message ? $request->message : '',
            'status' => $request->status,
            'carrier' => $request->carrier,
            'trackingNo' => $request->trackingNo,
        ]);

        if (isset($results->success) && $results->success) {
            return response()->json([
                'title' => __('cwp.requests.update.title'),
                'message' => __('cwp.requests.update.message'),
            ]);
        }

        return response()->json(['error' => $results, 'title' => 'Error']);
    }
}

app/Http/Controllers/Orders/OrderItemsController.php
<?php

namespace App\Http\Controllers\Orders;

use App\ABCorp\CWP\API\OrderItems;
use App\Http\Controllers\Controller;
use App\Http\Requests\PullActionsRequest;
use App\Traits\AdvancedSearch;
use Illuminate\Http\Request;

class OrderItemsController extends Controller
{
    use AdvancedSearch;

    private $orderItems;

    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            $this->orderItems = new OrderItems;

            return $next($request);
        });
    }

    /**
     * Get items list for the work order.
     *
     * @param string $work_order_uid
     * @param Request $request
     *
     * @return \Illuminate\View\View
     * @throws \Throwable
     */
    public function data(string $work_order_uid, Request $request)
    {
        $searchData = $this->orderItems->orderItems([
            'currentpage'  => 1,
            'itemsPerPage' => 0,
            'workOrderUid' => $work_order_uid,
        ]);

        $data = $this->orderItems->orderItems([
            'currentpage'  => $this->getCurrentPage($request),
            'workOrderUid' => $work_order_uid,
            'searchFields' => $this->getSearchFields($searchData->searchFields),
        ]);

        $data = $this->orderItems->getItemsActions($data);

        return $this->response('pages.orders.items', $request, [
            'data'           => $data,
            'include_search' => $this->isIncludeSearch($data->searchFields),
            'countries'      => $this->orderItems->getCountries(),
            'work_order_uid' => $work_order_uid,
        ]);
    }

    /**
     * Get details for the order item.
     *
     * @param string $id
     *
     * @return \Illuminate\View\View
     */
    public function show(string $id)
    {
        $details = $this->orderItems->itemDetails($id);

        if (!isset($details->data)) {
            return response()->json(['error' => $details, 'title' => 'Error'], 400);
        }

        return view('pages.orders.items.details.data', compact('details'));
    }

    /**
     * Make a pull request.
     *
     * @param PullActionsRequest $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function action(PullActionsRequest $request)
    {
        $results = $this->orderItems->pullAction($request->all());

        if (is_array($results)) {
            return response()->json([
                'title'   => __('Pull request'),
                'message' => __('Your pull request has been successfully sent'),
            ]);
        }

        return response()->json(['error' => $results, 'title' => 'Error']);
    }

    /**
     * Get actions forms for item.
     *
     * @param string $item_uid
     * @param Request $request
     *
     * @return string
     * @throws \Throwable
     */
    public function actions(string $item_uid, Request $request)
    {
        $item_actions = $request->actions;

        $actions = $this->orderItems->getActions();

        return view('pages.orders.items.actions.tabs',
            compact('actions', 'item_actions', 'item_uid'))->render();
    }
}

app/Http/Controllers/Orders/ProductItemsController.php
<?php

namespace App\Http\Controllers\Orders;

use App\ABCorp\CWP\API\OrderItems;
use App\ABCorp\CWP\API\Product;
use App\Http\Controllers\Controller;
use App\Traits\AdvancedSearch;
use Illuminate\Http\Request;

class ProductItemsController extends Controller
{
    use AdvancedSearch;

    private $orderItems;

    private $product;

    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            $this->orderItems = new OrderItems;
            $this->product = new Product;

            return $next($request);
        });
    }

    /**
     * Get items list.
     *
     * @param Request $request
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\JsonResponse|\Illuminate\View\View
     * @throws \Throwable
     */
    public function data(Request $request)
    {
        $prodID = isset($request->products) ? $request->products : '';
        $vertical = isset($request->vertical) ? $request->vertical : '';

        $searchData = $this->orderItems->byProduct([
            'currentpage' => 1,
            'itemsPerPage' => 0,
            'prodID' => $prodID,
            'prodVerticalUid' => $vertical
        ]);

        if (!isset($searchData->data) && !request()->ajax()) {
            return view('pages.orders.products.index');
        }

        $data = $this->orderItems->byProduct([
            'prodVerticalUid' => $vertical,
            'currentpage' => $this->getCurrentPage($request),
            'prodID' => $prodID,
            'searchFields' => isset($searchData->searchFields) ? $this->getSearchFields($searchData->searchFields) : null,
        ]);

        $data = $this->orderItems->getItemsActions($data);

        if (isset($data->productVerticals)) {
            $verticals = [];

            foreach ($data->productVerticals as $vertical) {
                $products = [];

                foreach ($data->products as $product) {
                    if (in_array($product->key, $vertical->value->prodList)) {
                        $products[$product->key] = $product->value;
                    }
                }

                $verticals[$vertical->key] = [
                    'name' => $vertical->value->name,
                    'products' => $products
                ];
            }

            return $this->response('pages.orders.products', $request, [
                'data' => $data,
                'selectedVertical' => $data->selectProductVertical,
                'verticals' => $verticals,
                'include_search' => $this->isIncludeSearch($data->searchFields),
                'countries' => $this->orderItems->getCountries(),
            ]);
        }
    }
}

resources/views/pages/orders/products/index.blade.php
@extends('layouts.cwp')

@section('title', __('Product Items'))

@section('breadcrumb')
    <ol class="breadcrumb">
        <li>
            {{ __('Orders') }}
        </li>
        <li class="active">
            <strong>{{ __('Product Items') }}</strong>
        </li>
    </ol>
@endsection

@section('content')

    @if (isset($verticals))
        <div class="ibox-content m-b-md border-bottom p-top-xs-20 p-top-sm-20">

            <product-items verticals-list="{{ json_encode($verticals) }}"
                           current-vertical="{{ $selectedVertical }}"></product-items>

        </div>
    @endif

    @if (isset($data))
        <div id="table">
            @include('pages.orders.products.table')
        </div>

        @include('pages.orders.items.details.modal')

        @include('pages.orders.items.actions.modal')
    @else
        <div class="alert alert-warning m-n">
            {{ __('No data available.') }}
        </div>
    @endif

@endsection

@push('scripts')
    <script>
        var offset_first = true;

        $(document).ready(function () {
            DTinit();

            $('.chosen-select.verticals').change(function () {
                $('.chosen-select.products').val('');
                getData();
            });
        });
    </script>
@endpush

resources/views/pages/orders/products/table.blade.php
@if (isset($data->searchFields) and !empty($data->searchFields))
    @include('partials.advanced-search')
@endif

@component('partials.table', compact('data', 'pagination'))
    <table class="table table-striped table-bordered table-hover" id="dataTable">
        <thead>
        <tr>
            <th style="width: 30px"></th>
            @if (isset($data->data) && !empty($data->columns))
                @foreach($data->columns as $column)
                    <th @if ($column->maxWidth) style="width: {{ $column->maxWidth }}" @endif>
                        <div data-toggle="tooltip" data-placement="top" title="{{ $column->tooltips }}">
                            {{ $column->displayName }}
                        </div>
                    </th>
                @endforeach
                <th style="width: 75px;"></th>
            @endif
        </tr>
        </thead>
        <tbody>
        @foreach($data->data as $item)
            <tr>
                <td class="text-center">
                    @if ($item->_status->tooltips == 'Shipped')
                        <div data-toggle="tooltip" data-placement="top" title="Shipped"
                             style="color: {{ $item->_status->color }}">
                            <span style="color: #192f5a;">
		 	                    <i class="fa fa-circle fa-2x"></i>
		                    <span>
                        </div>
                    @elseif($item->_status->tooltips == 'Destroyed')
                        <div data-toggle="tooltip" data-placement="top" title="{{ $item->_status->tooltips }}"
                             style="color: {{ $item->_status->color }}">
                            <i class="fa fa-trash fa-2x" aria-hidden="true"></i>
                        </div>
                    @elseif($item->_status->tooltips == 'In Progress')
                        <div data-toggle="tooltip" data-placement="top" title="{{ $item->_status->tooltips }}"
                             style="color: {{ $item->_status->color }}">
                            <span style="color: lightblue;">
		 	                    <i class="fa fa-adjust fa-2x"></i>
		                    <span>
                        </div>
                    @elseif($item->_status->tooltips == 'Pending')
                        <div data-toggle="tooltip" data-placement="top" title="{{ $item->_status->tooltips }}"
                             style="color: {{ $item->_status->color }}">
                            <span style="color: lightblue;">
		 	                    <i class="fa fa-adjust fa-2x"></i>
                            <span>
                        </div>
                    @elseif($item->_status->tooltips == 'Not Available')
                        <div data-toggle="tooltip" data-placement="top" title="Not Started"
                            style="color: {{ $item->_status->color }}">
                            <span style="color: lightblue;">
		 	                    <i class="fa fa-circle-thin fa-2x"></i>
		                    <span>
                        </div>
                    @elseif($item->_status->tooltips == 'Rejected')
                        <div data-toggle="tooltip" data-placement="top" title="{{ $item->_status->tooltips }}"
                             style="color: {{ $item->_status->color }}">
                            <i class="fa fa-times-circle fa-2x" aria-hidden="true"></i>
                        </div>
                    @elseif($item->_status->tooltips == 'Returned')
                        <div data-toggle="tooltip" data-placement="top" title="{{ $item->_status->tooltips }}"
                             style="color: {{ $item->_status->color }}">
                            <i class="fa fa-history fa-2x" aria-hidden="true"></i>
                        </div>
                    @else
                        <div data-toggle="tooltip" data-placement="top" title="Not Started"
                             style="color: {{ $item->_status->color }}">
                            <span style="color: lightblue;">
                                <i class="fa fa-circle-thin fa-2x"></i>
		                    <span>
                        </div>
                    @endif
                </td>
                @foreach(get_object_vars($data->columns) as $key => $value)
                    <td>{{ $item->{$key} }}</td>
                @endforeach
                <td class="text-center">
                    <div style="width: 90px">
                        <button type="button" class="btn btn-outline btn-info order-items-details"
                                title="{{ __('Details') }}"
                                data-details-url="{{ route('order-items.show', ['order_item' => $item->_uid]) }}">
                            <i class="fa fa-info" aria-hidden="true"></i>
                        </button>

                        @if (!empty(json_decode($item->actions)))
                            <button type="button" class="btn btn-outline btn-primary pull-action"
                                    data-actions="{{ $item->actions }}" title="{{ __('Actions') }}"
                                    data-action-url="{{ route('order-items.actions', ['item_uid' => $item->_uid]) }}">
                                <i class="fa fa-cog" aria-hidden="true"></i>
                            </button>
                        @endif
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endcomponent